name: mmoInfoGold
version: ${releaseVersion}.${buildNumber}
description: Adds a {gold} token to the mmoInfo token list.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.MMOInfoGold
depend: [Spout, mmoCore, mmoInfo, Vault]

permissions:
    mmo.info.gold:
        description: Allows {gold} to show the current player gold (from Vault)
        default: op
