name: mmoInfoGold
main: mmo.Info.MMOInfoGold
version: 1.0
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore,mmoInfo,Vault]

description: Adds {gold} to the info tokens
permissions:
  mmo.info.gold:
    description: Allows {gold} to show the current player gold (from Vault)
    default: true
